apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: react-nginx-route
  namespace: ingress
spec:
  parentRefs:
  - name: react-nginx-gateway
  hostnames:
  - "app-internal.teste.com"
  rules:
  - backendRefs:
    - name: react-nginx-service
      port: 80
