apiVersion: v1
kind: Service
metadata:
  name: react-nginx
  namespace: app
  labels:
    app: app
    env: hml
spec:
  selector:       #Quais pods vão ser expostos
    app: app    #Seleciona os Pods com essa label
  ports:
  - port: 80      #Porta do serviço
    name: http
    targetPort: 8080   #A porta onde o cluster tá escutando
  type: ClusterIP