name: Terraform

on:
  workflow_dispatch: 
    inputs: #Criar o imput para passar a imagem
        terraform:      #nome do meu imput
          description: pipeline manual de terraform #descricao
          type: choice
          options:
          - init
          - plan
          - apply
          - destroy


jobs:
  terraform_init:
    runs-on: ubuntu-latest
   
    
    steps:
       
      - name: Checkout
        uses: actions/checkout@v3



      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Autenticar no GCP
        env:
          GCP_KEY: ${{ secrets.GCP_SA_KEY }}
        run: |
          echo "$GCP_KEY" > /tmp/gcp-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
          gcloud config set project playground-s-11-f23c9032


      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        working-directory: ./projeto-02-docker-nginx/terraform
        run: terraform init

      - name: Terraform Plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        if: github.event.inputs.terraform == 'plan' || github.event.inputs.terraform == 'apply'
        working-directory: ./projeto-02-docker-nginx/terraform
        run: terraform plan

      - name: Terraform Apply
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        if: github.event.inputs.terraform == 'apply'
        working-directory: ./projeto-02-docker-nginx/terraform
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        env:
          GOOGLE_APPLICATION_CREDENTIALS: /tmp/gcp-key.json
        if: github.event.inputs.terraform == 'destroy'
        working-directory: ./projeto-02-docker-nginx/terraform
        run: terraform destroy -auto-approve



     
